### ISSUE TITLE
Zoom feature doesn't work with free-cam mode

### ISSUE THREAD

**Issue by magneticflux-** [maruohon/multishot#4]
The zoom level is applied all the time, instead of only when a screenshot is being taken.

Version: 1.12.0-3.2.1
Forge Version: 1.12-14.21.1.2420

**Comment by magneticflux-** [comment]
Additionally, the reverse occurs: When sprinting, the timelapse FOV grows and shrinks suddenly.

**Comment by magneticflux-** [comment]
@maruohon You can use the `EntityViewRenderEvent.FOVModifier` event handler to intercept FOVs and adjust them based on if the entity is your free cam entity. At least, that's what it looks like after hunting through some rendering methods. I'm not sure if there's any catch, but it's a start.

**Comment by magneticflux-** [comment]
Here's a quick fix to get you started:
```
    @SubscribeEvent
    @SideOnly(Side.CLIENT)
    public void onFOVModifier(EntityViewRenderEvent.FOVModifier event) {
        if (event.getEntity() == cameraEntity) {
            event.setFOV(Minecraft.getMinecraft().gameSettings.fovSetting);
        }
    }
```
Just paste that inside the `RenderEventHandler` class. It sets the freecam's FOV to the user's setting, but it can be re-purposed for your own FOV setting easily.

**Comment by maruohon** [comment]
I uploaded a new release, let me know if it still has issues. I forgot to test the sprinting case, but at least both the first person and the free camera modes now work with the "Zoom" feature otherwise.
