### ISSUE TITLE
Allow users without the mod to connect to servers with the mod

### ISSUE THREAD

**Issue by magneticflux-** [maruohon/multishot#5]

**Comment by maruohon** [comment]
I'm confused. This mod is client-side only, so what exactly isn't working related to this?

**Comment by magneticflux-** [comment]
@maruohon When a user tries to connect to a world that is opened to LAN, they are rejected.

**Comment by maruohon** [comment]
Oh, right... I hadn't thought of that case.

**Comment by magneticflux-** [comment]
@maruohon Other than that and the FOV thing, it's been working great so far! Thanks for your work on this mod!
